[greeter]
background=/usr/share/backgrounds/thakhin/greeter.png
theme-name=Adwaita-dark
icon-theme-name=Adwaita
font-name=Padauk 11
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%H:%M — သခင် OS
default-user-image=/usr/share/pixmaps/thakhinos.png
