# Thakhin OS neofetch configuration
print_info() {
    info title
    info underline

    info "OS" distro
    prin "ဥက္ကဋ္ဌကြီး" "ဝင်းကိုကိုလတ် (AnonyLatt ဌာနကြီး)"
    prin "အသင်း" "တောသားနှိမ်နင်းရေးအသင်း | MTC"
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "DE" de
    info "CPU" cpu
    info "Memory" memory
    prin "ဆောင်ပုဒ်" "အမျိုးကိုစောင့်၊ ဘာသာကိုစောင့်၊ သာသနာကိုစောင့်"
    prin "Website" "winkokolatt.me"

    info cols
}

distro_shorthand="off"
os_arch="on"
uptime_shorthand="on"
memory_percent="on"

image_backend="ascii"
image_source="/usr/share/thakhin-os/ascii-logo.txt"
ascii_colors=(3 11)
colors=(3 7 3 3 7 7)
underline_char="═"
separator=" ➤"
