#!/bin/bash
# Runs INSIDE the privileged debian:bookworm container.
# /src     = thakhin-os build dir (rw, for dist output)
# /website = winkokolatt.me site crawl (ro)
# THAKHIN_ARCH = amd64 | arm64
set -euxo pipefail

export DEBIAN_FRONTEND=noninteractive
ARCH="${THAKHIN_ARCH:-amd64}"

# Self-log to the bind-mounted dist/ so the build survives host/session restarts
# (container runs detached; the log + ISO land on the host regardless).
mkdir -p /src/dist
rm -f "/src/dist/DONE-$ARCH" "/src/dist/FAILED-$ARCH"
exec > >(tee "/src/dist/build-$ARCH.log") 2>&1
trap 'rc=$?; echo "==== BUILD FAILED ($ARCH) rc=$rc ===="; touch "/src/dist/FAILED-$ARCH"' ERR

echo "==== [1/6] Installing build tooling (arch=$ARCH) ===="
apt-get update
apt-get install -y --no-install-recommends \
  live-build debootstrap xorriso squashfs-tools mtools dosfstools \
  imagemagick libmagickcore-6.q16-6-extra librsvg2-bin \
  fonts-noto-core fonts-sil-padauk fonts-dejavu \
  curl ca-certificates rsync file

# Build on container-native FS (virtiofs bind mounts cannot hold a chroot)
BUILD=/build
rm -rf "$BUILD"; mkdir -p "$BUILD"
cp -a /src/config "$BUILD/config"
mkdir -p "$BUILD/config/includes.chroot/usr/share/thakhin-os/website"

echo "==== [2/6] Bundling winkokolatt.me website into the OS ===="
rsync -a --exclude 'thakhin-os' --exclude '.git' /website/ \
  "$BUILD/config/includes.chroot/usr/share/thakhin-os/website/"

echo "==== [3/6] Generating branding art ===="
bash /src/container/gen-art.sh "$BUILD"

echo "==== [4/6] Customising bootloader templates ===="
TPL=/usr/share/live/build/bootloaders
mkdir -p "$BUILD/config/bootloaders"
for bl in isolinux syslinux_common grub-pc; do
  if [ -d "$TPL/$bl" ] && [ ! -d "$BUILD/config/bootloaders/$bl" ]; then
    cp -a "$TPL/$bl" "$BUILD/config/bootloaders/$bl"
  fi
done

# --- syslinux/isolinux: BIOS boot menu (amd64 only; arm64 has no syslinux) ---
if [ "$ARCH" = "amd64" ]; then
  SYN="$BUILD/config/bootloaders/syslinux_common"
  rm -f "$SYN/splash.svg"
  cp "$BUILD/art/splash-640.png" "$SYN/splash.png"
  cp "$BUILD/art/splash-800.png" "$SYN/splash800x600.png"
  sed -i 's/Live system/Thakhin OS 1.0 Live/g' "$SYN/live.cfg.in"
  sed -i 's/menu title Boot menu/menu title Thakhin OS 1.0 - Anti-Tarzan Community Edition/' "$SYN/menu.cfg"
  sed -i 's/#ffffffff #76a1d0ff/#ff0d0d0d #ffd4af37/g' "$SYN/stdmenu.cfg"
fi

# --- GRUB: UEFI boot menu (both arches) ---
GP="$BUILD/config/bootloaders/grub-pc"
[ -d "$GP" ] && cp "$BUILD/art/splash-800.png" "$GP/splash.png" || true
[ -f "$GP/live-theme/theme.txt" ] && \
  sed -i 's/^title-text:.*/title-text: "Thakhin OS 1.0 - Anti-Tarzan Community Edition"/' \
  "$GP/live-theme/theme.txt" || true
# Menu-entry labels are generated by live-build itself — rebrand the generator
[ -f /usr/lib/live/build/binary_grub_cfg ] && \
  sed -i 's/Live system/Thakhin OS 1.0 Live/g' /usr/lib/live/build/binary_grub_cfg || true

echo "==== [5/6] live-build configure (arch=$ARCH) ===="
cd "$BUILD"

# arch-specific knobs: amd64 = BIOS+UEFI hybrid w/ syslinux; arm64 = UEFI/GRUB only
if [ "$ARCH" = "amd64" ]; then
  BINIMG=iso-hybrid
  BOOTLOADERS="syslinux,grub-efi"
else
  BINIMG=iso
  BOOTLOADERS="grub-efi"
fi

lb config noauto \
  --architectures "$ARCH" \
  --distribution bookworm \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images "$BINIMG" \
  --bootloaders "$BOOTLOADERS" \
  --debian-installer none \
  --memtest none \
  --apt-recommends true \
  --compression gzip \
  --bootappend-live "boot=live components quiet splash username=thakhin hostname=thakhin-os locales=en_US.UTF-8 keyboard-layouts=us live-config.timezone=Asia/Yangon live-config.user-default-groups=audio,cdrom,dip,floppy,video,plugdev,netdev,scanner,bluetooth,sudo,docker,wireshark,nopasswdlogin" \
  --iso-application "Thakhin OS 1.0 - Anti-Tarzan Community Edition" \
  --iso-publisher "Anti-Tarzan Association; Chairman Win Ko Ko Latt (AnonyLatt Dept.)" \
  --iso-volume "THAKHIN_OS_1_0_$ARCH"

echo "==== [6/6] live-build build (this is the long part) ===="
lb build

ls -lh "$BUILD"/*.iso
mkdir -p /src/dist
OUT="/src/dist/ThakhinOS-1.0-$ARCH.iso"
for iso in "$BUILD"/*.iso; do cp -v "$iso" "$OUT"; done
( cd /src/dist && sha256sum "ThakhinOS-1.0-$ARCH.iso" | tee "ThakhinOS-1.0-$ARCH.iso.sha256" )
touch "/src/dist/DONE-$ARCH"
echo "==== BUILD COMPLETE ($ARCH) ===="
